language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda create --yes -n condaenv pip
  - source activate condaenv
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy nose
  - pip install python-coveralls nose-cov climate skdata theano
  - pip install .
script:
  - nosetests --with-cov --cov theanets --cov-config .coveragerc --logging-level=INFO
after_success:
  - coveralls --config_file .coveragerc
