language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
 - sudo apt-get install -qq libblas-dev liblapack-dev gfortran
install:
  - "pip install -r requirements.txt"
  - "pip install ."
script: nosetests
