language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
  - travis_retry pip install -U pip numpy scipy theano pep8 nose python-coveralls
  - travis_retry python setup.py develop
script: nosetests --with-coverage --cover-package=theanets
after_success:
  - coveralls
cache: apt
