language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
  - pip install skdata
  - pip install .
script:
  - nosetests
